# Set tmux color to be able to display One Dark theme
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

# Set the prefix key to C-a instead of C-b
# Worth to have because of nested terminal
set -g prefix C-a

# Start window numbering at 1
set -g base-index 1

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# # Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Use prefix + : for status keys
set -g status-keys emacs

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Vim mode
set-window-option -g mode-keys vi

# Disable paste time
set -g assume-paste-time 0

# Get rid of jumping cursor
set -g repeat-time 0

# Enable mouse for scrolling and other cool stuff.
# Man cannot live in terminal forever.
set -g mouse on

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
