# Colors (One Dark)
[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 14

# ~/.config/alacritty/alacritty.toml
[general]
	import = ["rose-pine-moon.toml"]

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" }
]
